- Server/app/pdfEndpoints.py
- Server/app/scoring_logic.py
- Webapp/src/components/competition/EventSelector.tsx
- Webapp/src/components/competition/HeatSelector.tsx
- Webapp/src/components/competition/PhaseSelector.tsx
- Webapp/src/components/roles/headJudge/headJudge.tsx
- Webapp/src/components/roles/scribe/InfoBar.tsx
- Webapp/src/components/roles/scribe/InfoBar/PaddlerSelector.tsx
- Webapp/src/components/roles/scribe/InfoBar/Runselector.tsx
- Webapp/src/components/roles/scribe/Scribe.tsx
- Add logic to stop a user providing a heat/phase/event with an empty name.
> Add logic to prevent submission of empty heat and phase names

- Server/app/pdfEndpoints.py
- Server/app/scoring_logic.py
- Webapp/src/components/competition/EventSelector.tsx
- Webapp/src/components/competition/HeatSelector.tsx
- Webapp/src/components/competition/PhaseSelector.tsx
- Webapp/src/components/roles/headJudge/headJudge.tsx
- Webapp/src/components/roles/scribe/InfoBar.tsx
- Webapp/src/components/roles/scribe/InfoBar/PaddlerSelector.tsx
- Webapp/src/components/roles/scribe/InfoBar/Runselector.tsx
- Webapp/src/components/roles/scribe/MoveCard.tsx
- Webapp/src/components/roles/scribe/Scribe.tsx
- Webapp/src/redux/services/emptyApi.ts
- Add logic to prefetch ScoredMoveCard info when the MoveCard is rendered, so that the ScoredMoveCard renders immediately when it is scored.
- Add retry policy with exponential backoff to all rtk-query calls.
> Prefetch scored move info

- Webapp/src/components/competition/PhaseScoretable.tsx
- Skip phase call if the phase is not populated
> Remove unneeded phase endpoint

- Server/app/competition_management/competition_management.py
- Server/app/competition_management/tests/test_competition_management.py
Fix type error on promote-phase
> Fix UUID/String type error

- Webapp/src/components/competition/PromotePhase.tsx
- Webapp/src/components/header/Header.tsx
- Webapp/src/components/roles/scribe/InfoBar/ScoredMove.tsx
-  Improve layout of promote-phase component
- Add explanation of behaviour if the cut-off athlete is tied.
- Add link to homepage on app icon
- Increase size of user role
- Add boldness to direction in scored move card
> Visual fixes

- Webapp/src/components/competition/HeatSummaryTable.tsx
- Webapp/src/components/judging/JudgingPage.tsx
- Webapp/src/components/roles/headJudge/headJudge.tsx
- Webapp/src/components/roles/scribe/InfoBar/PaddlerSelector.tsx
- Webapp/src/components/roles/scribe/Scribe.tsx
- Add skip token to stop calls being made if heat is not selected. #26
> Stop useless and failling calls to API being made

- Webapp/src/components/roles/scribe/InfoBar/Runselector.tsx
- Webapp/src/components/roles/scribe/Scribe.tsx
- Improve number of runs logic so that the max number of runs in the heat is used
- Add red indicator if run is invalid for paddler
> Improve number of runs logic

- Webapp/src/components/ScoresheetBuilder/AddScoresheet.tsx
- Webapp/src/components/ScoresheetBuilder/ScoresheetBuilderPage.tsx
- Webapp/src/components/competition/CompetitionSelector.tsx
- Webapp/src/components/competition/EventSelector.tsx
- Webapp/src/components/competition/HeatSelector.tsx
- Webapp/src/components/competition/PhaseSelector.tsx
- Webapp/src/pages/Admin.tsx
- Add phase update
- Tidy up formatting on Scoresheet Builder and Admin Pages
- Change selectors to use Dividers rather than <hr>'s
> - Add update option for phase

- Server/app/scoring/customScoringEndpoints.py
- Server/pyproject.toml
- Fix type hint
- Fix broken type
- Add mypy extension to give better intellisense.
> Fix type hint

- Server/app/competition_management/pdfEndpoints.py
Fixed issue where multi heat PDF would only display one PDF.
> FIX: fixed indentation issue on PDF endpoints

- .devcontainer/.env
- Server/db/client.py
- docker-compose.yaml
- Remove unnecessary singleton thread pool class
- Update to specify DB driver
As per https://docs.sqlalchemy.org/en/13/core/engines.html#postgresql
Closes #47
> Possible fix of DB session issues

- Server/data/icf.json
- remove superclean on woo tricky
resolves #52
> Remove superclean on woo-tricky

- Server/data/icf.json
Remove Pistol Flip
resolves #53
> Remove Pistol Flip

- Webapp/src/components/roles/headJudge/headJudge.tsx
- Change head judge polling interval
closes #57
> Change Head Judge page polling interval to 1s

- Server/data/icf.json
> Update bonuses on tricky loop

- Webapp/src/components/roles/scribe/InfoBar/PaddlerSelector.tsx
- Webapp/src/components/roles/scribe/InfoBar/Runselector.tsx
Make Bib and Run numbers larger, so that the Chief judge can check them easily.
> Make bib number and run number larger

- Server/app/scoring/customScoringEndpoints.py
- Server/app/scoring/scoring_logic.py
- Server/app/scoring/tests/test_scoring_logic.py
- Webapp/src/utils/scoringUtils.ts
- Update logic so that all bonuses scored against that move type/direction combination are included in the score for a move.
- Verify scores are the same in the frontend and backend
- Add unit test
resolves #44
> Update scored move logic

- Webapp/src/components/competition/MakeHeatPDFs.tsx
> Clear selected heats between competitions for Create Many Heat Selector

- Server/app/competition_management/pdfEndpoints.py
> Order heat PDFs in Create Mant Heat PDFs by name

- Webapp/src/components/competition/CompetitionSelector.tsx
- Webapp/src/components/competition/EventSelector.tsx
- Webapp/src/components/competition/HeatSelector.tsx
- Webapp/src/components/competition/PhaseSelector.tsx
> Add refresh icons to selectors

- Server/app/competition_management/competition_management.py
- Server/app/scoring/customScoringEndpoints.py
- Webapp/src/components/competition/HeatScoreTable.tsx
- Webapp/src/components/roles/headJudge/headJudge.tsx
- Webapp/src/components/roles/scribe/Scribe.tsx
- Websockety fixes
- Update head judge subscription to use websockets rather than polling http
> Update scored moves to head judge using websockets

- Server/app/scoring/customScoringEndpoints.py
- Server/app/scoring/scoring_logic.py
- Server/app/scoring/tests/test_scoring_logic.py
Make Python scores match correct JS scores
Add additional unit test
> Fix python scores

- Webapp/src/components/competition/CompetitionSelector.tsx
- Webapp/src/components/competition/EventSelector.tsx
- Webapp/src/components/competition/HeatSelector.tsx
- Webapp/src/components/competition/PhaseSelector.tsx
- Webapp/src/components/competition/RefreshIconButton.tsx
- Add refresh icon for when there are no entries in a selector
- Refactor code to use common component
> Add refresh when there are no entries in a form

- Webapp/src/components/competition/HeatScoreTable.tsx
- Webapp/src/components/roles/headJudge/headJudge.tsx
- Add scorecard to head judge page showing the mean score for the run, with DNS/Lock indicators
> Add Final Score to head judge screen

- Server/main.py
- docker-compose.yaml
- Add health endpoint to server
- Add health checks to docker compose
> Add health checks to docker compose

- .devcontainer/setupEnvs.sh
- Server/Dockerfile
- Server/custom_logging.py
- Server/main.py
- Server/pyproject.toml
- docker-compose.yaml
- Update to use gunicorn with some replicas in production
- Update logging to remove datadog dependency, and just use a UUID as a correlation ID.
- Update logging to write to a mounted volume, making it easier to check from the host machine.
resolves #150
> Update server config

- Webapp/src/components/roles/headJudge/headJudge.tsx
> Add color coding to run status buttons

- Server/app/common/tests/test_websocket_handler.py
- Server/app/common/websocket_handler.py
- Server/app/scoring/customScoringEndpoints.py
- Add connection manager
- Add tests for connection manager
- Update code to use connection manager.
resolves #143
> Use websocket connection handler

- Server/app/scoring/customScoringEndpoints.py
- Webapp/src/components/roles/headJudge/WebSocketConnections.ts
- docker-compose.yaml
- nginx.conf
- Fix Websocket API string to be correct and more robust
- Set workers on server to 1, so that we don't have multiple lists of clients
- Adjust headers on server to not time out after 60s
> Websocket Hotfix

- Server/app/scoring/customScoringEndpoints.py
- Server/app/scoring/scoring_logic.py
- Server/app/scoring/tests/test_scoring_logic.py
Fix logic error that meant that the lowest scoring ride wasn't counted by the tiebreak logic.
> Add tests for missing run scores

- Server/app/scoring/scoring_logic.py
- Server/app/scoring/tests/test_scoring_logic.py
> Fix scoring rounding to match ICF rules

- Server/.env.test
- Server/app/competition_management/tests/test_pdfEndpoints.py
- docs/architecture.md
- Add pdf endpoint tests
- Update Docs
> Add PDF Endpoint tests

- Server/app/scoring/scoring_logic.py
- Server/data/icf_2025.json
- Webapp/src/utils/scoringUtils.ts
> Fix move values based on feedback from ICF judge

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/setupEnvs.sh
- .gitignore
- Server/Dockerfile
- Server/README.md
- Server/uv.lock
- docs/decisions/ADR001-record-architectural-decisions.md
- docs/decisions/ADR002-use-uv-for-package-management.md
- Change to use UV in devcontainer and prod
- Add ADR to record decision
> Change to uv as python package manager

- Server/app/competition_management/tests/test_pdfEndpoints.py
- Server/app/conftest.py
- Server/app/scoring/tests/test_customScoringEndpoints.py
- Server/app/scoring/tests/test_scoring_logic.py
- Server/pyproject.toml
- Server/pytest.ini
- Server/tests/conftest.py
- Webapp/src/components/competition/__tests__/CompetitionSelector.test.tsx
- Webapp/src/components/competition/__tests__/HeatScoreTable.test.tsx
- Fix frontend and backend linting issues
> Fix lint issues

- Webapp/src/components/roles/headJudge/headJudge.tsx
- Webapp/src/components/roles/scribe/Scribe.tsx
Add logic to refetch on component mount to avoid stale cached data being presented when the user navigates back to the page
> Update run status refetch logic to fetch on mount

- Webapp/src/components/roles/headJudge/JudgeCard.tsx
- Webapp/src/components/roles/headJudge/headJudge.tsx
> Use updater function to make state updates more robust

- Server/app/competition_management/create_competition_from_xlsx.py
- Server/app/competition_management/tests/test_create_competition_from_xlsx.py
- Webapp/src/components/competition/UploadCsv.tsx
- Add optional last phase rank handling to csv upload
- Update UI spec for CSV
- Add tests
> Add optional last phase ranks to csv upload

- Webapp/src/components/ScoresheetBuilder/AddScoresheet.tsx
- Webapp/src/components/competition/CompetitionSelector.tsx
- Fix type issues from version updates
> fix type issues

- Webapp/src/components/roles/headJudge/LiveTimer.tsx
- Webapp/src/components/roles/headJudge/__tests__/LiveTimer.test.tsx
- round live time
- add unit tests
> Round live time

- Timer/src/timer.py
> Operation goose

- Server/app/common/websocket_handler.py
- Webapp/src/components/arena/arena.tsx
- Webapp/src/components/arena/arenaTheme.tsx
- Webapp/src/components/arena/liveTimerArena.tsx
- Webapp/src/components/broadcast/Cards/AthleteInfoCard.tsx
- Webapp/src/components/broadcast/Cards/BasicBroadcastTable.tsx
- Webapp/src/components/broadcast/Cards/EventTitle.tsx
- Webapp/src/components/broadcast/Cards/HeatSummaryTable.tsx
- Webapp/src/components/broadcast/Cards/LiveRunScore.tsx
- Webapp/src/components/broadcast/Cards/PhaseResultsTable.tsx
- Webapp/src/components/broadcast/Cards/RunCard.tsx
- Webapp/src/components/broadcast/SlidingModal.tsx
- Webapp/src/components/broadcast/controller.tsx
- Webapp/src/components/broadcast/overlay.tsx
- Webapp/src/components/roles/headJudge/FinalScore.tsx
- Webapp/src/components/roles/headJudge/JudgeCard.tsx
- Webapp/src/components/roles/headJudge/LiveTimer.tsx
- Webapp/src/pages/Arena.tsx
> Initial arena screen

- Webapp/package-lock.json
- Webapp/package.json
> Revert "build(deps): Bump the npm_and_yarn group across 1 directory with 2 updates"
